---
title: "Memo 1"
author: "* Team AMIE *"
date: "*February 11, 2019*"
output: pdf_document
---

** Members: **
* Ann-Marie Stringer (ams670) ams670@georgetown.edu 
* Ivy Deng (xd66) xd66@georgetown.edu
* Erich Denk (ed719) ed719@georgetown.edu


** Github Repository: ** https://github.com/ErichDenk/Team_AMIE_670_Project

#** Problem Statement **

In 2015, there were an estimated 1.1 million people living with HIV in the United States. In 2016, there were almost 40,000 new cases of HIV. More than half of new HIV diagnoses in 2016 occurred in the Southern States, whose total population account for only 38% of the national population. 1 of 10 of new diagnoses in 2016 was attributable to injection drug use (HIV.gov 2017).  

Syringe services programs (SSPs), also referred to as needle exchange programs (NEPs) provide sterile needles and syringes to drug users and safely dispose of used needles and syringes as a preventative measure for HIV and other infections that are transmissible by blood. Many of these programs also integrate other intervention strategies, such as testing, treatment, and counseling services. 

As of 2014, 33 states had explicitly banned SSPs, and the federal funding of SSPs was prohibited.  In 2016, the law was changed to allow jurisdictions to use federal funding to support certain components of SSPs, excluding the purchase of the actual syringe and needles. Despite this new legal opportunity, SSPs remain a controversial topic with strong opposition. Opponents to SSPs believe that federal funding of these programs indicates approval of illegal drug use, will lead to an increase in drug use and will lessen the moral and logistical barrier of access for children to become users (Weinmeyer 2016). Despite the research and evidence that has been presented to oppose these viewpoints, adequate SSPs are still not available. 

A CDC report stated that “although the percentage of persons who inject drugs (PWID) in 22 cities who received syringes from a syringe services program increased during 2005–2015 for all racial/ethnic groups (p<0.001), less than one-third of PWID received all their syringes from sterile sources” (Wejnert 2016) . While SSPs do exist in many cities, particularly in the North East, these services are not sufficient to meet the needs of injection drug users, particularly in rural areas and in states without legal support of such programs. 

In this study, we aim to explore the data related to HIV incidence (with a focus on transmission via injection drug use), legal barriers for SSPs by state, levels of stigma towards HIV/drug use by state/county, and prevalence of SSPs by state/county in order to gain a holistic understanding of the unmet need for SSPs in the United States, particularly in the rural south. These are important questions to consider and their answers may help better inform policymaking and program funding.  

#** Data **

In our exploration of SSPs a number of data sources will be helpful. First, data regarding the incidence of HIV is available via [AIDSVu](https://map.aidsvu.org/map). For example, their “All-State PrEP Data Sets” contains information regarding pre-exposure prophylaxis user rates may be of interest. The data is available across a number of different years, allowing an examination of trends of HIV incidence from time periods of interest, such as before or after a policy change. In regards to SSPs and NEPs, the North America Syringe Exchange Network in cooperation with [amfAR](https://opioid.amfar.org/indicator/num_SSPs) provides an extensive, though not completely comprehensive listing of needle exchange programs throughout the country. Each dataset contains geographic identifiers to allow comparison across areas. We will be able to make urban-rural and regional comparisons in regards to both HIV incidence and prevention policies. These datasets provide the geographic and time dimensions that will be particularly helpful in examining our tentative research questions.

#** Potential Issues **
Several data limitations are likely to impede the present study. First, due to confidentiality reasons, the latest data on HIV diagnosis at the county-level may not be available for public use. Second, the prevalence of undiagnosed HIV results in under-estimated data on HIV prevalence. Persons with undiagnosed HIV contribute to nearly 30% of its transmission in the US. In 2011, 14% of the 1.2 million people living with HIV had infections that were undiagnosed. Lastly, the percentage of persons living with HIV who had received a diagnosis of HIV infection varied by jurisdiction. Persons who are infected with HIV may move from one jurisdiction to another. As estimates of HIV prevalence are based on the most recent known address, delays or errors in reporting residential addresses might result in measurement errors of the data. Inaccurate or incomplete data is likely to induce biases to our final estimates of the effect of SSPs on reducing HIV transmission.


#** Works Cited **
HIV.gov. 2018. “HIV U.S. Statistics.” HIV.Gov. July 11, 2018. https://www.hiv.gov/hiv-basics/overview/data-and-trends/statistics.

Weinmeyer, Richard. 2016. “Needle Exchange Programs’ Status in US Politics.” AMA Journal of Ethics 18 (3): 252–57. https://doi.org/10.1001/journalofethics.2017.18.3.hlaw1-1603.

Wejnert, Cyprian. 2016. “Vital Signs: Trends in HIV Diagnoses, Risk Behaviors, and Prevention Among Persons Who Inject Drugs — United States.” MMWR. Morbidity and Mortality Weekly Report 65. https://doi.org/10.15585/mmwr.mm6547e1.

