---
title: "ZCTA"
author: "Ann Marie Stringer"
date: "April 12, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(urbnmapr)
require(devtools)
library(tidyverse)
require(here)
require(rgdal)
```

read in/clean data frame for relevant variables
```{r}
tidyData <- read.csv(here("Active-data-sets/2015-Prevalence-IDU-data.csv")) %>%
  mutate(County = as.character(County))%>%
  select(., county_name = County, State, PercentIDU)

sspLocation <- read.csv(here("Active-data-sets/sspLocationLatLong.csv")) %>%
  select(., state, latitude, longitude) 
```

map
```{r}
mapData <- left_join(tidyData, counties, by = "county_name")

a = data.frame("West" = c("WA", "OR", "CA", "NV", "UT", "ID", "MT", "WY", "CO", NA, NA, NA, NA, NA), Southwest = c("TX", "AZ", "NM", "OK", NA, NA,NA,NA,NA,NA,NA,NA,NA,NA), Midwest = c("ND", "SD", "NE", "KS", "MO", "IL", "IA", "MN", "WI", "MI", "OH", "IN", NA, NA), Southeast = c("AR", "LA", "AL", "MS", "GA", "FL", "SC", "NC", "TN", "KY", "VA", "DE", "MD", "WV"), Northeast = c("PA", "NJ", "CT", "NY", "RI", "VT", "NH", "MA", "ME", NA,NA,NA,NA,NA))

a

West <- c("WA", "OR", "CA", "NV", "UT", "ID", "MT", "WY", "CO")

Southwest <- c("TX", "AZ", "NM", "OK")

Midwest <- c("ND", "SD", "NE", "KS", "MO", "IL", "IA", "MN", "WI", "MI", "OH", "IN")

Southeast <- c("AR", "LA", "AL", "MS", "GA", "FL", "SC", "NC", "TN", "KY", "VA", "DE", "MD", "WV")

Northeast <- c("PA", "NJ", "CT", "NY", "RI", "VT", "NH", "MA", "ME")

USA <- c(West, Southwest, Midwest, Southeast, Northeast) 

a = USA

mapData %>%
  # first layer plots states 
  ggplot(data = states[states$state_abbv %in% a,], mapping = aes(long, lat, group=group)) + 
  # center the map view on the US
  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
  # black boarder and grey fill for all states
  geom_polygon(color = "black", fill = "grey") +
  # adding the IDU as the density fill per county
  geom_polygon(data = mapData[mapData$state_abbv %in% a,], aes(fill = PercentIDU)) +
  #change gradient for scale bar -- I wanted darker color to be higher IDU density. 
  scale_fill_gradientn( colors = c("white", "blue"),
                       guide = guide_colorbar(title.position = "top"))+
  # re plot the black boarder lines
  geom_polygon(color = "black", fill = NA) +
  geom_point(data=sspLocation[sspLocation$state %in% a,], mapping =aes(x=longitude, y=latitude), inherit.aes = FALSE)

#would be good to have a toggle for if you want ssp location on or off -- so we can see the chloropleth better


```

```{r}
stateSSPnum <- 
  sspLocation %>%
  select(., state) %>%
  mutate(., State= as.character(state)) %>%
  group_by(State) %>%
  count(.)

prevAve <-  read.csv(here("Active-data-sets/2015-Prevalence-IDU-data.csv")) %>%
  select(., State, CountyPrevalence, TotalIDU) %>%
  mutate(State = as.character(State)) %>%
  na.omit() %>%
  group_by(State) %>%
  summarize(., totalIDU = sum(TotalIDU)) 

sspPlot <- full_join(prevAve, stateSSPnum, by = "State") %>%
  #mutate(., sspNum = replace(.$n, is.na(.$n), 0)) %>%
  mutate(., totalIDU = replace(.$totalIDU, .$totalIDU==0, NA)) %>%
  mutate(., sspAvail = totalIDU/n) %>%
  select(State, sspAvail) %>%
  na.omit()


ggplot(sspPlot, aes(State, sspAvail)) +
  geom_col()

```

```{r}
Law = read.csv(here("Active-data-sets/syringe-exchange-laws-clean.csv")) %>%
  select(State, Legal = Yes) 

convertAbbr <- states %>%
  select(state_abbv, state_name) %>%
  group_by(state_abbv, state_name) %>%
  count(.) %>% 
  select(state_abbv, State = state_name)

LawDat <- left_join(Law, convertAbbr, by = "State") %>%
  select(State = state_abbv, Legal) %>%
  write.csv(here("Active-data-sets/legal-data-for-map"), row.names=F)

ggplot(Law, aes(State, Legal)) +
  geom_col()
```

