---
title: "SSP data to map"
author: "Ann Marie"
date: "4/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require(here)
require(tidyverse)
require(zipcode)
```


```{r}
sspDat <- read.csv(here("Active-data-sets/SSP-Location-Data")) %>%
  mutate(city = as.character(City), state = as.character(State)) %>%
  select(X, city, state)
```

```{r}
data(zipcode.civicspace)
zip <- zipcode.civicspace %>% 
  select(city, state, latitude, longitude) %>% 
  distinct(.) 

zip <- zip[!duplicated(zip[c("city","state")]),]


sspCoord <- right_join(zip, sspDat, by = c("city", "state")) %>%
  na.omit(.) %>% 
  filter(., state !="HI", state != "PR", state != "AK") %>%
  select(., state, latitude, longitude) 

#should be 237, but only 222 were recognized by the zip package. lost 6%... will revisit if time. 
# took out AK, HI, PR for mapping ease... will revisit this if time as well
write.csv(sspCoord, here("Active-data-sets/sspLocationLatLong.csv"))

```

```{r}
stateSSPnum <- 
    sspCoord %>%
    select(., state) %>%
    mutate(., State= as.character(state)) %>%
    group_by(State) %>%
    count(.)

prevAve <-  read.csv(here("Active-data-sets/2015-Prevalence-IDU-data.csv")) %>%
    select(., State, CountyPrevalence, TotalIDU) %>%
    mutate(State = as.character(State)) %>%
    na.omit() %>%
    group_by(State) %>%
    summarize(., totalIDU = sum(TotalIDU)) 

sspPlot <- full_join(prevAve, stateSSPnum, by = "State") %>%
    #mutate(., sspNum = replace(.$n, is.na(.$n), 0)) %>%
    mutate(., totalIDU = replace(.$totalIDU, .$totalIDU==0, NA)) %>%
    mutate(., sspAvail = totalIDU/n) %>%
    select(State, sspAvail, totalIDU)

LawDat <-  read.csv(here("Active-data-sets/legal-data-for-map"))

sspCol <-  full_join(sspPlot, LawDat, by = "State") %>%
  mutate(Legal = ifelse(.$Legal == 1, "Legal", "Not Legal")) %>%
    mutate(sspExist = ifelse(is.na(.$sspAvail), "No SSPs in state", "At least one SSP in state")) %>%
    mutate(sspBurden = ifelse(is.na(.$sspAvail), .$totalIDU, .$sspAvail)) %>%
    mutate(sspBurden = ifelse(is.na(.$sspBurden), 0, .$sspBurden)) %>%
  select(State, sspBurden, Legal, sspExist) %>%
  arrange(-sspBurden)

write.csv(sspCol, here("Active-data-sets/sspDensity.csv"))

```

