---
title: "prevalence aidsvu data set"
author: "Ann Marie Stringer"
date: "April 11, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Packages
```{r}
require(tidyverse)
require(xlsx)
require(here)
```

```{r}
prevData <- read.xlsx(here("SSP-data-set/AIDSVu_County_Prev-Data-Sets_2015.xlsx"), sheetName = "Data", startRow = 3) 
```

Going to clean out some of the less-relevant data for our interests, initial data stored in prevData in case we want to go back to it. 
Want to keep the following columns
- GEO ID (might be useful for mapping, not sure what it is though not Zip code, but ZCTA??)
- State Abbreviation
- County Name 
- County Cases 
- total IDU cases
```{r}
tidyData <- prevData %>%
  select(GEOID = "GEO.ID", State = "State.Abbreviation", County = "County.Name", CountyPrevalence = "County.Cases", TotalIDU = "IDU.Total.Cases")  %>%
  mutate(TotalIDU = as.numeric(as.character(TotalIDU))) %>%
  mutate(PercentIDU = ((TotalIDU/CountyPrevalence)*100))

```
```{r}
write.csv(tidyData, here("SSP-data-set/2015-Prevalence-IDU-data.csv"))
```

